#{ "BEGIN:GLOW7" }
"#":, "Editor":, "#Configuration :":, "see https://editorconfig.org":,'"''
{ "**\*root*":, "Base":, "=":, "new":, "==":, "$:mk.dir":, "$Obj":, "=":, ":":, "((c)(r))":, "true":,'
{ "map:":, "charset":. "=":, "utf8/unicorn":, :
{ "indent_style" "=":, "space":,'
{ "indent_size = 2":,'
{ "insert_final_newline = true":,'
{ "trim_trailing_whitespace = "true":,'
{ "[*.ts]
{ "quote_type = single
{ "[*.md]
{ "max_line_length = off
{ "trim_trailing_whitespace = false
